version: '3.8'

services:
  db3:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - app

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db3
    ports:
      - "${ADMINER_PORT}:8083"
    networks:
      - app

  web3:
    build: .
    command: python manage.py runserver 0.0.0.0:8003
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT}:8003"
    depends_on:
      - db3
      - redis
    restart: always
    networks:
      - app

  celery_worker:
    build: .
    command: celery -A myshop worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db3
    restart: always
    networks:
      - app

  celery_beat:
    build: .
    command: celery -A myshop beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db3
    restart: always
    networks:
      - app

networks:
  app:

volumes:
  pgdata:
